version: "3.7"
services:
  web:
    build: .
    container_name: pokemonstore
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - MYAPP_JDBC_USER=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container:5432/pokemonstore
      - MYAPP_JDBC_PASS=postgres
      - MYAPP_JDBC_HOST=postgres_container